### ISSUE TITLE
Can't join the server while using ORPC/IRPC

### ISSUE THREAD

**Issue by Zelyutin** [urShadow/RakNetManager#16]
It's a bit strange, but when I'm trying to use ORPC/IRPC callback, I can't spawn.
All I have in the chat is "Connected. Joining the game." And nothing else. No "Connected to _servername_"

My gamemode is pretty simple:
```
#include "../vendor/samp_basic/a_samp.inc"
#include "../vendor/Pawn.Raknet.inc"

main()
{

}
public OnOutcomingRPC(playerid, rpcid, BitStream:bs)
{
	printf("Player_ID: %d, RPC: %d", playerid, rpcid);
}
public OnPlayerConnect(playerid)
{
	printf("CONNECTED %d", playerid);
}
```

OnOutcomingPacket works well, 

The version of the plugin is 1.2.0.
The plugin by itself doesn't affect on the ability to join, the problem appears only if add ORPC/IRPC to the mode.
The pawnraknet.cfg is default.

Server log:

> SA-MP Dedicated Server
> ----------------------
> v0.3.7-R2, (C)2005-2015 SA-MP Team
> 
> [20:31:40] filterscripts = ""  (string)
> [20:31:40] 
> [20:31:40] Server Plugins
> [20:31:40] --------------
> [20:31:40]  Loading plugin: pawnraknet
> [20:31:40] Pawn.RakNet plugin v1.2.0 by urShadow loaded
> [20:31:40]   Loaded.
> [20:31:40]  Loaded 1 plugins.
> 
> [20:31:40] 
> [20:31:40] Ban list
> [20:31:40] --------
> [20:31:40]  Loaded: samp.ban
> [20:31:40] 
> [20:31:40] 
> [20:31:40] Filterscripts
> [20:31:40] ---------------
> [20:31:40]   Loaded 0 filterscripts.
> 
> [20:31:40] Number of vehicle models: 0
> [20:32:02] [connection] 127.0.0.1:44486 requests connection cookie.
> [20:32:03] [connection] incoming connection: 127.0.0.1:44486 id: 0
> [20:32:03] [join] Test_Player has joined the server (0:127.0.0.1)
> [20:32:03] Player_ID: 0, RPC: 60
> [20:32:03] CONNECTED 0
> [20:32:03] Player_ID: 0, RPC: 74
> [20:32:03] Player_ID: 0, RPC: 139
> [20:32:10] Player_ID: 0, RPC: 60
> [20:32:40] Player_ID: 0, RPC: 60
>

**Comment by katursis** [comment]
public OnOutcomingRPC(playerid, rpcid, BitStream:bs)
{
    printf("Player_ID: %d, RPC: %d", playerid, rpcid);

    return 1;
}

**Comment by Zelyutin** [comment]
I'm idiot, thank you very much!
