### ISSUE TITLE
desync key crash with more 1 player online

### ISSUE THREAD

**Issue by RodrigoDornelles** [urShadow/RakNetManager#17]
if only one player is connected, the code works correctly (`KEY_FIRE` is not reported in `OnPlayerKeyStateChange`, and animation is cleanly prevented from using the view tool)

But when more than 1 player online, while holding the night vision glasses, the server shuts down without logs (even with crash detect and logcore)

Is there a problem with the  code?

```const PLAYER_SYNC = 207; 
static VarOldKey[MAX_PLAYERS]; 

IPacket:PLAYER_SYNC(playerid, BitStream:bs) 
{ 
   if(!(43 < GetPlayerWeapon(playerid) < 46)) 
       return 1; 

   new newkeys; 

   BS_IgnoreBits(bs, 40); 
   BS_ReadValue(bs, PR_UINT16, newkeys);  

        
   if(((newkeys & (KEY_FIRE)) == (KEY_FIRE)) && ((VarOldKey[playerid] & (KEY_FIRE)) != (KEY_FIRE))) 
       ClearAnimations(playerid); 

    VarOldKey[playerid]=newkeys; 
    if(newkeys & (KEY_FIRE)) 
       newkeys &= ~KEY_FIRE; 

   BS_SetReadOffset(bs, 40);   
   BS_WriteValue(bs,PR_UINT16, newkeys); 
   return 1; 
} 
```
> the wiki exemple SetPlayerDisableKeysSync works, but I did not choose it, to use only the necessary one without extra verifications, and recet of functions

**Comment by zottce** [comment]
can you set a write offset instead of read one at the end of your function?

**Comment by RodrigoDornelles** [comment]
@ZOTTCE thanks, this was the problem that was occurring
