### ISSUE TITLE
bug RPC

### ISSUE THREAD

**Issue by MDShift** [urShadow/RakNetManager#21]
new BitStream:b = BS_New();
	BS_WriteValue(b, PR_UINT8, vehicleid, PR_FLOAT, vx, PR_FLOAT, vy, PR_FLOAT, vz);
	BS_RPC(b, playerid, 91, PR_HIGH_PRIORITY, PR_RELIABLE);
	BS_Delete(b);
        SetVehicleVelocity = 91 rpcid))
        not working

**Comment by MDShift** [comment]
exemple
public OnIncomingPacket(playerid, packetid, BitStream:bs){ 
    if(packetid == 200){ 
                new vehicleid; 
        BS_IgnoreBits(bs, 8); 
        BS_ReadUint16(bs,vehicleid); 
         
                new BitStream:b = BS_New(); 
        BS_WriteValue(b, PR_UINT8, vehicleid, PR_FLOAT, 10.0, PR_FLOAT, 10.0, PR_FLOAT, 10.0); 
        BS_RPC(b, playerid, 91, PR_HIGH_PRIORITY, PR_RELIABLE); 
        BS_Delete(b); 
    } 
    return true; 
} 
SetVehicleVelocity = 91 rpcid 



  not working

**Comment by katursis** [comment]
vehicleid must be PR_UINT16.

**Comment by MDShift** [comment]
PR_UINT16 тоже не роботает))) там должно быть  PR_UINT8 или PR_INT8 потому что имеит рпк 104 битов)) 8+32+32+32 = 104

**Comment by katursis** [comment]
```pawn
new BitStream:b = BS_New();

BS_WriteValue(
    b, 
    PR_UINT8, 0, 
    PR_FLOAT, vx, 
    PR_FLOAT, vy, 
    PR_FLOAT, vz
);

BS_RPC(b, playerid, 91, PR_HIGH_PRIORITY, PR_RELIABLE);

BS_Delete(b);
```

**Comment by MDShift** [comment]
и так не роботает))) проверь сам)))
