### ISSUE TITLE
Question about "OnFootSync"

### ISSUE THREAD

**Issue by omcho420** [urShadow/RakNetManager#23]
I started using Pawn.RakNet a few days ago and while I was trying to create an anti-cheat for health/armour hack I noticed something, firstly I was not sure about opening an Issue about this but if I'm wrong u can just close this.

Why are PR_health and PR_armour integers and not floats?
I'm talking about the PR_OnFootSync enumator.

EDIT: I found the id's for all the packets

**Comment by katursis** [comment]
> Why are PR_health and PR_armour integers and not floats?

Because they store in a packet as integer.
