### ISSUE TITLE
Question about OPacket

### ISSUE THREAD

**Issue by User18172** [urShadow/RakNetManager#25]
Здравствуйте! Вопрос про разбор исходящих OnfootSync пакетов, а именно: кому отправляется пакет, мы можем определить из аргумента коллбэка, а как определить, какого игрока синхронизирует этот пакет?

**Comment by katursis** [comment]
Можно прочитать из пакета.

Сначала игнорируется 1 байт (PR_UINT8), содержащий packetId, затем читаются 2 байта (PR_UINT16), в которых хранится идентификатор синхронизируемого игрока.

**Comment by User18172** [comment]
Спасибо
