### ISSUE TITLE
GetPacketId not found

### ISSUE THREAD

**Issue by TamerGezici** [urShadow/RakNetManager#29]
503299 [18/04/2020 21:17:22]   Loaded.
503300 [18/04/2020 21:17:22]  Loading plugin: SKY.so
503301 [18/04/2020 21:17:22]   Loaded.
503302 [18/04/2020 21:17:22]  Loading plugin: pawnraknet.so
503303 [18/04/2020 21:17:22] [Pawn.RakNet] Load: GetPacketId not found
503304 [18/04/2020 21:17:22]   Failed.
503305 [18/04/2020 21:17:22]  Loaded 8 plugins.

Hello, I am kinda on the run and in a hurry, I haven't tried anything to fix it. Do you know what the solution is?

**Comment by katursis** [comment]
Try to load pawnraknet before SKY.

**Comment by TamerGezici** [comment]
Thanks for the fast reply. It's fixed now. Spasibo.

**Comment by katursis** [comment]
Tell me SKY version please.

**Comment by TamerGezici** [comment]
It's a very old version. From 2017 or 2016.
