### ISSUE TITLE
pawnraknet.cfg issue

### ISSUE THREAD

**Issue by Chaprnks** [urShadow/RakNetManager#30]
> ### Configuration (pawnraknet.cfg) 
> InterceptIncomingPacket (true)
> InterceptIncomingRPC (true)
> InterceptOutcomingPacket (true)
> InterceptOutcomingRPC (true)
> InterceptIncomingRawPacket (true)
> **UseCaching (false)**

I've noticed an issue with this config file, especially when altering then **UseCaching** field.

Changing this to true, crashes the server apon the first player connecting.

**Comment by katursis** [comment]
What other plugins are you using?

**Comment by Chaprnks** [comment]
`crash.so mysql.so sscanf.so streamer.so raknet.so colandreas.so cmd.so memory.so gps.so discord.so sky.so
`


Although, the crashlog refers to raknet plugin on the crash. All of this has no crash when caching is disabled.



```
[debug] #12 f5f54e5f in _ZN7Scripts13OnIncomingRPCEiiPN6RakNet9BitStreamE () in plugins/raknet.so
[debug] #13 f5f63adb in _ZN5Hooks13InternalHooks10ReceiveRPC7HandlerILj103EE10InterlayerEP13RPCParameters () in plugins/raknet.so
[debug] #17 f5f5e62f in _ZN5Hooks13InternalHooks18RakServer__ReceiveEPv () in plugins/raknet.so
```

**Comment by katursis** [comment]
**UseCaching** incompatible with YSI includes.

**Comment by Chaprnks** [comment]
Oh! Well that's good to know! Maybe we should have a "info/warning" message on the GitHub wiki stating that? Might save others time from having to repeat this.

**Comment by katursis** [comment]
Done.
