### ISSUE TITLE
gmx

### ISSUE THREAD

**Issue by f0Re3t** [urShadow/RakNetManager#5]
собственно с подключенным плагином и вызовом sendrconcommand("gmx") - сервер не включается, точнее он включается, но игроков не пускает. процесс доходит до connected и все. ничего больше не вызывается.

yandex translate:
actually connected plug-in and call sendrconcommand("gmx") - the server is not included, rather it is included, but players will not let me. the process comes to connected and everything. nothing else is called.

**Comment by katursis** [comment]
Fixed.

https://github.com/urShadow/RakNetManager/commit/f768eefc2f0d32fab16d411e07ccb3e993d70276
