### ISSUE TITLE
RPC ClientJoin - 25

### ISSUE THREAD

**Issue by UHPS** [urShadow/RakNetManager#52]
Опечатка в  - UINT32 uiClientChallengeResponse
Правильно - bool  uiClientChallengeResponse

**Comment by NexiusTailer** [comment]
В этом репозитории нет подобной информации. Возможно, вы о репо "samp-packet-list" с вики от Brunoo16?

**Comment by NexiusTailer** [comment]
Upd: Судя по тестам, с UINT32 там всё верно.
