### ISSUE TITLE
Gamemode breaking

### ISSUE THREAD

**Issue by Montrii** [urShadow/RakNetManager#56]
Greetings,

Using 1.5.0 right now, and my console throws me an error saying "(...) conflicting versions (1.5.0) and include (1.5.1) (...)".
That error causes the gamemode not to load at all, however my filterscript works just fine.

Removing the include from the gamemode fixes the issue and allows my gamemode to use raknet functions/callbacks.

Dont know if intended or a bug, but it seems like it uses the include frim the filterscript instead.

Cya.

**Comment by katursis** [comment]
Try 1.5.1.
