### ISSUE TITLE
Update to the open.mp beta server

### ISSUE THREAD

**Issue by nickdodd25** [urShadow/RakNetManager#61]
Open.mp beta was released today, Any chance this will be updated to support it?

**Comment by zottce** [comment]
double the request

**Comment by recepilhanli** [comment]
I agree, I hope it will be.

**Comment by katursis** [comment]
Yes, I'm going to do it soon.

**Comment by nickdodd25** [comment]
I was reading over the open multiplayer readme and it appears they are planning on adding what this plugin does directly to the server. That would be fantastic if they went that route.
