### ISSUE TITLE
Pawn.RakNet crashing with sampvoice

### ISSUE THREAD

**Issue by AbdulOmarCR** [urShadow/RakNetManager#72]
Hello, this is the backtrace of the crash:

#0  0xf7bf2b14 in ?? () from /lib/i386-linux-gnu/libc.so.6
#1  0xf631ce80 in Hooks::GetRakServerInterface() () from plugins/pawnraknet.so
#2  0xf6144878 in RakNet::GetRakServerInterfaceHook() () from plugins/sampvoice.so
#3  0x080af514 in ?? ()
#4  0x080aa0e6 in ?? ()
#5  0xf7abded5 in __libc_start_main () from /lib/i386-linux-gnu/libc.so.6
#6  0x0804b4e1 in ?? ()

**Comment by katursis** [comment]
https://github.com/katursis/Pawn.RakNet/issues/41#issuecomment-742511078
