### ISSUE TITLE
Пакеты не приходят

### ISSUE THREAD

**Issue by plakapenka** [urShadow/RakNetManager#83]
```
new BitStream:bitstream = BS_New();
		BS_WriteValue(
			bitstream, 
			PR_UINT8, 252,
			PR_UINT32, RPC_TOGGLE_CHOOSE_SPAWN,
			PR_UINT8, 1,
			PR_UINT8, Org_available,
			PR_UINT8, Station_available,
			PR_UINT8, Lastpos_available,
			PR_UINT8, Garage_available,
			PR_UINT8, House_available
		);
PR_SendPacket(bitstream, playerid, PR_SYSTEM_PRIORITY, PR_RELIABLE);

		printf("send RPC_TOGGLE_CHOOSE_SPAWN");
		BS_Delete(bitstream);
```

Вот простая отправка. Я получаю в консоль лог. Все хорошо.

Логирую самый верх получения, без чего-либо лишнего, в клиенте, и ничего не получаю
```
void CNetGame::UpdateNetwork() {

    Packet *pkt = nullptr;
    unsigned char packetIdentifier;

    while (pkt = m_pRakClient->Receive()) {
        packetIdentifier = GetPacketID(pkt);
        Log("reciev = %d", GetPacketID(pkt));
```

Это происходит не всегда. Примерно 1 раз из 10.
Этого не было на sa-mp. Стало происходить при переходе на омп. Я так же общался с человеком которые испытывает такие же проблемы при переходе на омп.

PR_RELIABLE вообще работает?

Буду рад любым мыслям по этому поводу

Я использую версию плагина 1.6.0. Версия omp RC2

**Comment by katursis** [comment]
С этим лучше зайти к разработчикам omp.

**Comment by plakapenka** [comment]
так же отправил и им ссылку на данный вопрос. Нет уверенности чья именно вина

**Comment by plakapenka** [comment]
@katursis но разве PR_RELIABLE  в любом случае не должен был повторить отправку, если подтверждение не получено?

**Comment by katursis** [comment]
Проблема не на уровне плагина, а на уровне реализации omp. API omp не позволяет выбирать значение reliability при отправке пакета. И priority, кстати, тоже.

https://github.com/openmultiplayer/open.mp-sdk/blob/master/include/player.hpp#L425

**Comment by plakapenka** [comment]
Ну и код... Как в плане логики так и в плане оформления
![image](https://github.com/katursis/Pawn.RakNet/assets/10694250/0e0bc3a5-f643-4960-82c3-88dc496053a1)

Это можно пофиксить и с твоей стороны, добавив такое же **дерьмо**. Но надеюсь все же пофиксят omp

Не закрывай пока issue. Я отправил его  omp

**Comment by plakapenka** [comment]
@katursis они сказали что не будут исправлять это у себя. У тебя есть желание пофиксить это на своей стороне, устанавливая каналы? Либо не ждать и делать это непосредственно в моде?..

**Comment by plakapenka** [comment]
я попробовал их подход. это действительно решает проблему.

Очень разочарован что они сделали такое лютое дерьмище и забрали у меня и других ребят столько времени на выяснение причин .

Для других:
я поставил параметр по умолчанию, в функциях include PawnRakNet, чтобы не возиться с этим. Это не правильно, но черт.. тут уже ничего не правильно

```
native PR_SendPacket(BitStream:bs, playerid, PR_PacketPriority:priority = PR_HIGH_PRIORITY, PR_PacketReliability:reliability = PR_RELIABLE_ORDERED, orderingchannel = 4);
native PR_SendRPC(BitStream:bs, playerid, rpcid, PR_PacketPriority:priority = PR_HIGH_PRIORITY, PR_PacketReliability:reliability = PR_RELIABLE_ORDERED, orderingchannel = 4);
```

Спасибо за помощь
