### ISSUE TITLE
Emulate packets open.mp read offset

### ISSUE THREAD

**Issue by dockfries** [urShadow/RakNetManager#92]
see `legacy_network_impl.cpp` 

https://github.com/openmultiplayer/open.mp/blob/8c246565edd6363ee55dfd01043f5c0c48f92f09/Server/Components/LegacyNetwork/legacy_network_impl.cpp#L917

```c++
bs.SetReadOffset(8); // Ignore packet ID
return handler->onReceivePacket(*player, type, bs);
```

but in `script.cc`, line 142, 155, 190, 203
https://github.com/katursis/Pawn.RakNet/blob/d2fef5af377ad090dd47908e13f170da33983119/src/script.cc#L140

```c++
bs->resetReadPointer(); // forget ignore packet ID ? --- bs->SetReadOffset(8); 
return handler->onReceivePacket(*player, packet_id, *bs);
```

`handler->onReceivePacket and handler->onReceive`

test it this way
1. connectNpc(foo), and assume that the id of this npc is 0
2. emulate an onFootSync packet and call the PR_EmulateIncomingPacket, params set playerid to 0.
3. get the npc position, if they are approach to where you just set.

**Comment by dockfries** [comment]
test case
```ts
import { GameMode, Npc, Player, PlayerEvent, SpecialActionsEnum } from "@infernus/core"
import { BitStream, IPacket, OnFootSync } from "@infernus/raknet"


GameMode.onInit((e) => {
  Npc.connectNPC('test', 'any_rec_file')
})

PlayerEvent.onSpawn(({player, next}) => {
  player.setPos(Math.random(), Math.random(), Math.random() + 3)
  player.setSpecialAction(SpecialActionsEnum.USEJETPACK)
  return next()
})

IPacket(207, (e) => {
  if(e.playerId !== 0) return true;
  return false;
})

setInterval(() => {
  const my = Player.getInstance(1)
  if(!my) return;
  const pos = my.getPos()
  console.log(pos)
  if(!pos) return;

  const quat = my.getRotationQuat()

  const vel = my.getVelocity()

  const bs = new OnFootSync(new BitStream());
  bs.writeSync(
    {
      lrKey: 0,
      udKey: 0,
      surfingVehicleId: 0,
      animationId: 0,
      animationFlags: 0,
      keys: 0,
      position: [pos.x - 0.5, pos.y,pos.z],
      quaternion: [quat.w, quat.x, quat.y, quat.z],
      health: 100,
      armour: 100,
      additionalKey: 0,
      weaponId: 0,
      specialAction: 0,
      velocity: [vel.x, vel.y, vel.z],
      surfingOffsets: [0, 0, 0]
    }
  )
  bs.emulateIncomingPacket(0)
  console.log(bs.readSync())
  bs.delete()

  console.log(Player.getInstance(0)?.getPos())
  console.log(Player.getInstance(0)?.getRotationQuat())
  console.log(Player.getInstance(0)?.getVelocity())
}, 1000)
```

**Comment by katursis** [comment]
Thank you for your contribution.

1) I'm concerned about old commits being present. Let's fix it so this PR only contains your changes.
2) Have you personally tested that the emulation works as expected with your changes?
3) I think the proposed changes should not affect PR_EmulateIncomingRPC, because BitStream RPC doesn't have a packetid at the beginning.
4) The bs->resetReadPointer() call can be removed if bs->SetReadOffset(8) is added.

**Comment by dockfries** [comment]
I tested (samp-node) in my environment, but I didn't try to write in native .pwn.
I found this issue because when I tried to call emulate natives, the data packet seemed to have an error offset.
For example, I clearly set the player's position, but data was wrong.

If `resetReadPointer` is redundant, let's remove it.
